import type { Testimonial } from "../types";

export const MOCK_TESTIMONIALS: Testimonial[] = [
  { id: "test-1", name: "Sarah Chen", role: "CTO", company: "TechCorp Inc.", avatar: "", content: "John is the most talented developer I've worked with. He architected our entire microservices migration and delivered ahead of schedule. His code quality and attention to detail are exceptional.", rating: 5, featured: true, source: "LinkedIn", date: "2026-06-15", order: 1, createdAt: "2026-06-15" },
  { id: "test-2", name: "Michael Rodriguez", role: "Product Manager", company: "StartupXYZ", avatar: "", content: "Working with John was a game-changer for our product. He built our MVP from scratch and it was production-ready in 3 months. Our investors were impressed by the quality and scalability.", rating: 5, featured: true, source: "Email", date: "2026-05-20", order: 2, createdAt: "2026-05-20" },
  { id: "test-3", name: "Emily Watson", role: "Founder", company: "WebAgency Pro", avatar: "", content: "John delivered exceptional work on multiple client projects. His ability to understand requirements and translate them into elegant solutions is remarkable. Highly recommended for any full-stack role.", rating: 5, featured: true, source: "LinkedIn", date: "2026-04-10", order: 3, createdAt: "2026-04-10" },
  { id: "test-4", name: "David Kim", role: "Engineering Manager", company: "BigCo Inc.", avatar: "", content: "John contributed significantly to our platform's frontend architecture. His React expertise and mentoring of junior developers made a lasting impact on our team.", rating: 4, featured: false, source: "Email", date: "2026-03-05", order: 4, createdAt: "2026-03-05" },
  { id: "test-5", name: "Lisa Thompson", role: "CEO", company: "DesignStudio", avatar: "", content: "John is the go-to developer for complex projects. He built our entire e-commerce platform and it has been running flawlessly for over a year. Exceptional problem-solving skills.", rating: 5, featured: false, source: "Upwork", date: "2026-02-15", order: 5, createdAt: "2026-02-15" },
  { id: "test-6", name: "Alex Patel", role: "Tech Lead", company: "FinTech Solutions", avatar: "", content: "John's work on our analytics dashboard was outstanding. He optimized queries that reduced load times by 60% and built a beautiful, intuitive UI that our clients love.", rating: 5, featured: false, source: "GitHub", date: "2026-01-20", order: 6, createdAt: "2026-01-20" },
  { id: "test-7", name: "Rachel Green", role: "Director of Engineering", company: "CloudScale", avatar: "", content: "I hired John for multiple freelance projects and he consistently exceeded expectations. His communication and project management skills are as strong as his technical abilities.", rating: 4, featured: false, source: "Upwork", date: "2025-12-10", order: 7, createdAt: "2025-12-10" },
  { id: "test-8", name: "Tom Bradley", role: "Co-founder", company: "AI Startup", avatar: "", content: "John's work on our AI platform was critical to our launch success. He integrated complex ML models into a user-friendly interface that our customers find intuitive.", rating: 5, featured: false, source: "LinkedIn", date: "2025-11-05", order: 8, createdAt: "2025-11-05" },
];
