import type { Certificate } from "../types";

export const MOCK_CERTIFICATES: Certificate[] = [
  { id: "cert-1", name: "AWS Solutions Architect – Associate", provider: "aws", providerLabel: "AWS", description: "Design distributed systems on AWS. Validates ability to architect and deploy secure and robust applications.", issueDate: "2025-03-15", expiryDate: "2028-03-15", credentialId: "AWS-ASA-8472", credentialUrl: "https://aws.amazon.com/verify", skills: ["AWS", "Cloud Architecture", "Microservices", "Security"], image: "", order: 1, createdAt: "2026-01-10" },
  { id: "cert-2", name: "Google Cloud Professional Developer", provider: "google", providerLabel: "Google Cloud", description: "Design, develop, and manage scalable Google Cloud solutions.", issueDate: "2025-06-20", expiryDate: "2028-06-20", credentialId: "GCP-DEV-3921", credentialUrl: "https://google.com/verify", skills: ["GCP", "Kubernetes", "Cloud Run", "Cloud Functions"], image: "", order: 2, createdAt: "2026-01-10" },
  { id: "cert-3", name: "Deep Learning Specialization", provider: "coursera", providerLabel: "Coursera", description: "Comprehensive deep learning course by Andrew Ng covering neural networks, CNNs, RNNs, and transformers.", issueDate: "2024-09-01", expiryDate: null, credentialId: "DL-SPEC-5634", credentialUrl: "https://coursera.org/verify", skills: ["Deep Learning", "TensorFlow", "Python", "Neural Networks"], image: "", order: 3, createdAt: "2026-01-15" },
  { id: "cert-4", name: "Microsoft Azure Developer Associate", provider: "microsoft", providerLabel: "Microsoft", description: "Develop Azure compute solutions, implement Azure Functions, and manage storage.", issueDate: "2025-01-10", expiryDate: "2027-01-10", credentialId: "AZ-204-7182", credentialUrl: "https://learn.microsoft.com/verify", skills: ["Azure", "Azure Functions", "Cosmos DB", "DevOps"], image: "", order: 4, createdAt: "2026-02-01" },
  { id: "cert-5", name: "React – The Complete Guide", provider: "udemy", providerLabel: "Udemy", description: "Comprehensive React course covering hooks, context, Redux, Next.js, and testing.", issueDate: "2023-11-15", expiryDate: null, credentialId: "UC-REACT-2249", credentialUrl: "https://udemy.com/certificate", skills: ["React", "Redux", "Next.js", "TypeScript"], image: "", order: 5, createdAt: "2026-02-10" },
  { id: "cert-6", name: "Node.js Advanced", provider: "linkedin", providerLabel: "LinkedIn Learning", description: "Advanced Node.js concepts including streams, clustering, worker threads, and performance.", issueDate: "2024-04-20", expiryDate: null, credentialId: "LI-NODE-5631", credentialUrl: "https://linkedin.com/learning", skills: ["Node.js", "Express", "Performance", "Streams"], image: "", order: 6, createdAt: "2026-02-20" },
  { id: "cert-7", name: "Kubernetes Administrator (CKA)", provider: "other", providerLabel: "CNCF", description: "Demonstrates proficiency in Kubernetes cluster administration, networking, and security.", issueDate: "2025-08-05", expiryDate: "2028-08-05", credentialId: "CKA-9472-2025", credentialUrl: "https://cncf.io/verify", skills: ["Kubernetes", "Docker", "Cluster Management", "Security"], image: "", order: 7, createdAt: "2026-03-01" },
  { id: "cert-8", name: "TensorFlow Developer Certificate", provider: "other", providerLabel: "TensorFlow", description: "Validates proficiency in building and training machine learning models with TensorFlow.", issueDate: "2024-12-10", expiryDate: null, credentialId: "TF-DEV-3847", credentialUrl: "https://tensorflow.org/verify", skills: ["TensorFlow", "ML", "Keras", "Python"], image: "", order: 8, createdAt: "2026-03-15" },
];
