export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/api/auth/login",
    REGISTER: "/api/register",
    LOGOUT: "/api/auth/logout",
    VERIFY_EMAIL: "/api/auth/verify-email",
    FORGOT_PASSWORD: "/api/auth/forgot-password",
    RESET_PASSWORD: "/api/auth/reset-password",
    VALIDATE_TOKEN: "/api/auth/validate-token",
    TWO_FACTOR_SETUP: "/api/auth/2fa/setup",
    TWO_FACTOR_VERIFY: "/api/auth/2fa/verify",
    SESSION: "/api/auth/session",
  },
  PORTFOLIO: {
    PROJECTS: "/api/projects",
    PROJECT_BY_ID: (id: string) => `/api/projects/${id}`,
    SKILLS: "/api/skills",
    SKILL_BY_ID: (id: string) => `/api/skills/${id}`,
    EXPERIENCE: "/api/experience",
    EXPERIENCE_BY_ID: (id: string) => `/api/experience/${id}`,
    SETTINGS: "/api/settings",
    SETTINGS_PUBLIC: "/api/settings/public",
  },
  CHAT: {
    MESSAGES: "/api/chat",
    ADMIN_USERS: "/api/chat/admin",
    AI: "/api/chat/ai",
    PORTFOLIO_AI: "/api/chat/portfolio",
  },
  CONTACT: "/api/contact",
  BLOG: {
    POSTS: "/api/blog",
    LIKE: "/api/blog/like",
    COMMENT: "/api/blog/comment",
  },
  ADMIN: {
    USERS: "/api/admin/users",
    SETTINGS: "/api/admin/settings",
    ACTIVITY: "/api/admin/activity",
    SYSTEM_HEALTH: "/api/admin/system-health",
    STATS: "/api/admin/stats",
    OLLAMA_HEALTH: "/api/admin/system-health/ollama",
    RESOURCE: (resource: string) => `/api/admin/${resource}`,
    AI_OPTIMIZE_PROJECT: "/api/admin/ai/optimize-project",
    AI_GENERATE_BLOG: "/api/admin/ai/generate-blog",
  },
  NOTIFICATIONS: "/api/notifications",
  CLOUDINARY_SIGN: "/api/cloudinary/sign",
  HEALTH: "/api/health",
  SEED: "/api/seed",
  GITHUB: {
    STATS: "/api/github/stats",
    REPOS: "/api/github/repos",
    USER: "/api/github/user",
    LANGUAGES: "/api/github/languages",
    REPO: (repo: string) => `/api/github/repo/${repo}`,
  },
  CERTIFICATES: "/api/certificates",
  TESTIMONIALS: "/api/testimonials",
  ACHIEVEMENTS: "/api/achievements",
  SOCIAL_LINKS: "/api/social-links",
  RESUME: "/api/resume",
} as const;
