export const seedAchievements = [
  {
    title: "Top 10 Hackathon Winner",
    description: "Won 1st place at the National AI Hackathon for building an AI-powered healthcare diagnostics tool in 48 hours.",
    category: "Competition",
    icon: "trophy",
    date: "2024-11",
    issuer: "TechFest Bangladesh",
    url: "",
    featured: true,
    order: 1,
  },
  {
    title: "Open Source Contributor — 500+ Stars",
    description: "Built and maintained open-source projects accumulating over 500 GitHub stars across multiple repositories.",
    category: "Open Source",
    icon: "github",
    date: "2024-06",
    issuer: "GitHub",
    url: "https://github.com/sorujmahmud",
    featured: true,
    order: 2,
  },
  {
    title: "AWS Certified Solutions Architect",
    description: "Earned AWS Solutions Architect Associate certification demonstrating cloud architecture expertise.",
    category: "Certification",
    icon: "award",
    date: "2023-09",
    issuer: "Amazon Web Services",
    url: "",
    featured: true,
    order: 3,
  },
  {
    title: "Best AI Integration — DevSummit 2024",
    description: "Recognized for the best AI integration in a production application at the annual developer summit.",
    category: "Award",
    icon: "star",
    date: "2024-03",
    issuer: "DevSummit",
    url: "",
    featured: false,
    order: 4,
  },
  {
    title: "10K+ Portfolio Visitors",
    description: "Reached over 10,000 unique visitors on the personal portfolio website within the first 6 months.",
    category: "Milestone",
    icon: "trending-up",
    date: "2024-08",
    issuer: "",
    url: "",
    featured: false,
    order: 5,
  },
  {
    title: "Published Technical Author",
    description: "Published technical articles on AI/ML topics reaching over 50,000 readers across platforms.",
    category: "Writing",
    icon: "pen-tool",
    date: "2024-01",
    issuer: "Medium / Dev.to",
    url: "",
    featured: false,
    order: 6,
  },
];
