export const seedExperience = [
  {
    year: "2024-Present",
    role: "AI Engineer & Full-Stack Developer",
    company: "Freelance / Consulting",
    description: "Building AI-powered applications and full-stack solutions for clients. Specializing in RAG systems, LLM integration, and scalable web architectures.",
    technologies: ["Next.js", "LangChain", "OpenAI", "MongoDB", "Vector DBs", "Docker", "AWS"],
    icon: "brain",
    color: "#8B5CF6",
    order: 1,
  },
  {
    year: "2022-2024",
    role: "Senior Full-Stack Developer",
    company: "Tech Startup Inc.",
    description: "Led development of multiple SaaS products. Architected microservices, implemented CI/CD pipelines, and mentored junior developers.",
    technologies: ["React", "Node.js", "PostgreSQL", "Redis", "Kubernetes", "GraphQL"],
    icon: "briefcase",
    color: "#3B82F6",
    order: 2,
  },
  {
    year: "2020-2022",
    role: "Full-Stack Developer",
    company: "Digital Agency",
    description: "Built custom web applications for diverse clients. Worked with React, Vue, Node.js, and various databases. Implemented responsive designs and RESTful APIs.",
    technologies: ["React", "Vue.js", "Node.js", "MongoDB", "MySQL", "AWS"],
    icon: "code",
    color: "#10B981",
    order: 3,
  },
  {
    year: "2018-2020",
    role: "Junior Developer",
    company: "Software Company",
    description: "Started career building internal tools and client projects. Learned full-stack development, database design, and deployment workflows.",
    technologies: ["JavaScript", "PHP", "MySQL", "HTML/CSS", "Git", "Linux"],
    icon: "graduation-cap",
    color: "#F59E0B",
    order: 4,
  },
];