export const seedProjects = [
  {
    title: "AI-Powered Portfolio",
    description: "A full-stack portfolio with AI chat, RAG, and admin panel",
    fullDescription: "Built with Next.js 15, MongoDB, and LangChain. Features an AI assistant that can answer questions about my projects and experience using RAG (Retrieval-Augmented Generation).",
    image: "/projects/portfolio.jpg",
    technologies: ["Next.js", "TypeScript", "MongoDB", "LangChain", "OpenAI", "Tailwind CSS"],
    features: ["AI Chat Assistant", "Admin Panel", "RAG Implementation", "Real-time Analytics", "Blog System"],
    githubUrl: "https://github.com/sorujmahmud/portfolio",
    liveUrl: "https://soruj-mahmud.dev",
    category: "Full Stack",
    status: "completed",
    featured: true,
    difficulty: "Advanced",
    duration: "3 months",
    teamSize: "1",
    tags: ["AI", "Full Stack", "Portfolio"],
    emoji: "🤖",
    metaDescription: "AI-powered portfolio with chat assistant and admin panel",
    seoTitle: "AI Portfolio - Soruj Mahmud",
    overview: "A modern portfolio showcasing AI engineering and full-stack development skills.",
    architecture: "Microservices with Next.js App Router, MongoDB, and LangChain for AI features.",
  },
  {
    title: "E-Commerce Platform",
    description: "Scalable e-commerce solution with payment integration",
    fullDescription: "A complete e-commerce platform with cart, checkout, payment processing, order management, and admin dashboard.",
    image: "/projects/ecommerce.jpg",
    technologies: ["React", "Node.js", "PostgreSQL", "Stripe", "Redis"],
    features: ["Shopping Cart", "Stripe Payments", "Order Tracking", "Admin Dashboard", "Inventory Management"],
    githubUrl: "https://github.com/sorujmahmud/ecommerce",
    liveUrl: "https://shop.example.com",
    category: "Full Stack",
    status: "completed",
    featured: true,
    difficulty: "Advanced",
    duration: "4 months",
    teamSize: "1",
    tags: ["E-Commerce", "Payments", "Full Stack"],
    emoji: "🛒",
    metaDescription: "Scalable e-commerce platform with Stripe integration",
    seoTitle: "E-Commerce Platform - Soruj Mahmud",
    overview: "Production-ready e-commerce solution with modern tech stack.",
    architecture: "Monorepo with React frontend, Node.js API, PostgreSQL database, and Redis caching.",
  },
  {
    title: "Real-time Chat Application",
    description: "WebSocket-based chat with rooms, DMs, and file sharing",
    fullDescription: "A real-time messaging application with channels, direct messages, file uploads, reactions, and search.",
    image: "/projects/chat.jpg",
    technologies: ["React", "Socket.io", "Node.js", "MongoDB", "Redis"],
    features: ["Real-time Messaging", "Channels & DMs", "File Sharing", "Message Search", "Reactions"],
    githubUrl: "https://github.com/sorujmahmud/chat-app",
    liveUrl: "https://chat.example.com",
    category: "Full Stack",
    status: "completed",
    featured: false,
    difficulty: "Intermediate",
    duration: "2 months",
    teamSize: "2",
    tags: ["Real-time", "WebSockets", "Chat"],
    emoji: "💬",
    metaDescription: "Real-time chat application with Socket.io",
    seoTitle: "Chat App - Soruj Mahmud",
    overview: "Scalable real-time messaging platform.",
    architecture: "Socket.io for real-time, Redis for pub/sub, MongoDB for persistence.",
  },
];