export const seedSkills = [
  { name: "TypeScript", slug: "typescript", level: 95, icon: "typescript", color: "#3178C6", category: "Languages", yearsOfExperience: 5, order: 1, description: "Strong typing for JavaScript applications" },
  { name: "JavaScript", slug: "javascript", level: 98, icon: "javascript", color: "#F7DF1E", category: "Languages", yearsOfExperience: 7, order: 2, description: "Core web development language" },
  { name: "Python", slug: "python", level: 90, icon: "python", color: "#3776AB", category: "Languages", yearsOfExperience: 4, order: 3, description: "AI/ML and backend development" },
  { name: "Go", slug: "go", level: 75, icon: "go", color: "#00ADD8", category: "Languages", yearsOfExperience: 2, order: 4, description: "High-performance backend services" },
  { name: "Rust", slug: "rust", level: 60, icon: "rust", color: "#CE422B", category: "Languages", yearsOfExperience: 1, order: 5, description: "Systems programming and WASM" },
  { name: "Next.js", slug: "nextjs", level: 95, icon: "nextjs", color: "#000000", category: "Frameworks", yearsOfExperience: 4, order: 6, description: "React framework for production" },
  { name: "React", slug: "react", level: 98, icon: "react", color: "#61DAFB", category: "Frameworks", yearsOfExperience: 6, order: 7, description: "Component-based UI library" },
  { name: "Node.js", slug: "nodejs", level: 95, icon: "nodejs", color: "#339933", category: "Frameworks", yearsOfExperience: 6, order: 8, description: "JavaScript runtime for backend" },
  { name: "LangChain", slug: "langchain", level: 85, icon: "langchain", color: "#1C3C3C", category: "AI/ML", yearsOfExperience: 2, order: 9, description: "LLM application framework" },
  { name: "OpenAI API", slug: "openai", level: 90, icon: "openai", color: "#412991", category: "AI/ML", yearsOfExperience: 2, order: 10, description: "GPT models and embeddings" },
  { name: "Vector Databases", slug: "vector-db", level: 80, icon: "database", color: "#6366F1", category: "AI/ML", yearsOfExperience: 1, order: 11, description: "Pinecone, Weaviate, Chroma" },
  { name: "RAG", slug: "rag", level: 85, icon: "search", color: "#8B5CF6", category: "AI/ML", yearsOfExperience: 1, order: 12, description: "Retrieval-Augmented Generation" },
  { name: "MongoDB", slug: "mongodb", level: 90, icon: "mongodb", color: "#47A248", category: "Databases", yearsOfExperience: 5, order: 13, description: "Document database" },
  { name: "PostgreSQL", slug: "postgresql", level: 85, icon: "postgresql", color: "#336791", category: "Databases", yearsOfExperience: 4, order: 14, description: "Relational database" },
  { name: "Redis", slug: "redis", level: 80, icon: "redis", color: "#DC382D", category: "Databases", yearsOfExperience: 3, order: 15, description: "In-memory data store" },
  { name: "Docker", slug: "docker", level: 85, icon: "docker", color: "#2496ED", category: "DevOps", yearsOfExperience: 4, order: 16, description: "Containerization platform" },
  { name: "Kubernetes", slug: "kubernetes", level: 70, icon: "kubernetes", color: "#326CE5", category: "DevOps", yearsOfExperience: 2, order: 17, description: "Container orchestration" },
  { name: "AWS", slug: "aws", level: 80, icon: "aws", color: "#FF9900", category: "Cloud", yearsOfExperience: 3, order: 18, description: "Cloud computing platform" },
  { name: "Vercel", slug: "vercel", level: 90, icon: "vercel", color: "#000000", category: "Cloud", yearsOfExperience: 3, order: 19, description: "Frontend deployment platform" },
  { name: "Tailwind CSS", slug: "tailwind", level: 95, icon: "tailwind", color: "#06B6D4", category: "Tools", yearsOfExperience: 3, order: 20, description: "Utility-first CSS framework" },
  { name: "GraphQL", slug: "graphql", level: 75, icon: "graphql", color: "#E10098", category: "Tools", yearsOfExperience: 2, order: 21, description: "Query language for APIs" },
  { name: "REST APIs", slug: "rest", level: 95, icon: "api", color: "#FF6B6B", category: "Tools", yearsOfExperience: 6, order: 22, description: "RESTful API design" },
  { name: "WebSockets", slug: "websockets", level: 80, icon: "websocket", color: "#00ADD8", category: "Tools", yearsOfExperience: 3, order: 23, description: "Real-time communication" },
  { name: "Testing", slug: "testing", level: 80, icon: "testing", color: "#C21325", category: "Tools", yearsOfExperience: 4, order: 24, description: "Jest, Vitest, Playwright" },
  { name: "CI/CD", slug: "cicd", level: 85, icon: "github-actions", color: "#2088FF", category: "DevOps", yearsOfExperience: 4, order: 25, description: "GitHub Actions, GitLab CI" },
];