export const env = {
  API_BASE_URL: (process.env.NEXT_PUBLIC_API_BASE_URL || "") as string,
  MONGODB_URI: (process.env.MONGODB_URI || "mongodb://localhost:27017/full-stack-protfolio") as string,
  AUTH_SECRET: process.env.AUTH_SECRET as string,
  NEXTAUTH_URL: (process.env.NEXTAUTH_URL || "http://localhost:3000") as string,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID as string,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET as string,
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID as string,
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET as string,
  CLOUDINARY_CLOUD_NAME: process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME as string,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY as string,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET as string,
  SMTP_HOST: (process.env.SMTP_HOST || "smtp.gmail.com") as string,
  SMTP_PORT: parseInt(process.env.SMTP_PORT || "587", 10),
  SMTP_SECURE: process.env.SMTP_SECURE === "true",
  SMTP_USER: process.env.SMTP_USER as string,
  SMTP_PASS: process.env.SMTP_PASS as string,
  EMAIL_FROM: (process.env.EMAIL_FROM || "sorujmahmudb2h@gmail.com") as string,
  EMAIL_FROM_NAME: (process.env.EMAIL_FROM_NAME || "Soruj Mahmud") as string,
  RESEND_API_KEY: process.env.RESEND_API_KEY as string,
  GOOGLE_GENERATIVE_AI_API_KEY: process.env.GOOGLE_GENERATIVE_AI_API_KEY as string,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY as string,
  TAVILY_API_KEY: process.env.TAVILY_API_KEY as string,
  APP_URL: (process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000") as string,
} as const;
