import type { Achievement } from "../types";

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  { id: "ach-1", title: "Stack Overflow Top 1%", description: "Reached top 1% contributor on Stack Overflow with 10K+ reputation points across React and TypeScript tags.", category: "Community", icon: "award", date: "2026-06-15", issuer: "Stack Overflow", url: "https://stackoverflow.com", featured: true, order: 1, createdAt: "2026-06-15" },
  { id: "ach-2", title: "Open Source Contributor of the Year", description: "Recognized for significant contributions to 5 major open-source projects with 2K+ combined stars.", category: "Open Source", icon: "github", date: "2026-05-01", issuer: "GitHub Community", url: "https://github.com", featured: true, order: 2, createdAt: "2026-05-01" },
  { id: "ach-3", title: "Hackathon Winner – AI Assistant", description: "First place in 48-hour hackathon for building an AI-powered code review assistant using GPT-4 and LangChain.", category: "Hackathon", icon: "trophy", date: "2026-03-20", issuer: "TechConf 2026", featured: true, order: 3, createdAt: "2026-03-20" },
  { id: "ach-4", title: "Published Technical Author", description: "Authored 3 technical articles featured in JavaScript Weekly and Node.js Weekly newsletters with 50K+ combined reads.", category: "Writing", icon: "book", date: "2026-02-10", issuer: "Dev.to", url: "https://dev.to", featured: false, order: 4, createdAt: "2026-02-10" },
  { id: "ach-5", title: "Conference Speaker – React Summit", description: "Presented 'Building Scalable React Applications' at React Summit 2026 to an audience of 500+ developers.", category: "Speaking", icon: "mic", date: "2026-01-15", issuer: "React Summit", url: "https://reactsummit.com", featured: true, order: 5, createdAt: "2026-01-15" },
  { id: "ach-6", title: "Mentor of the Year", description: "Recognized for mentoring 20+ junior developers through a 6-month bootcamp program with 95% success rate.", category: "Mentorship", icon: "users", date: "2025-12-10", issuer: "CodeMentor Inc.", featured: false, order: 6, createdAt: "2025-12-10" },
  { id: "ach-7", title: "500+ GitHub Stars", description: "Portfolio CMS project crossed 500 GitHub stars with active community contributions and 50+ forks.", category: "Open Source", icon: "star", date: "2025-11-01", issuer: "GitHub", url: "https://github.com", featured: false, order: 7, createdAt: "2025-11-01" },
  { id: "ach-8", title: "Patent Pending – Distributed Cache", description: "Co-inventor on patent application for novel distributed caching algorithm improving hit rates by 35%.", category: "Innovation", icon: "patent", date: "2025-09-15", issuer: "USPTO", featured: false, order: 8, createdAt: "2025-09-15" },
];
